jobs:
  build:
    docker:
    - auth:
        password: $DOCKERHUB_PASSWORD
        username: circle4regentmarkets
      image: regentmarkets/debian-ci:stable
      user: nobody
    steps:
    - add_ssh_keys:
        fingerprints:
        - 26:72:b1:08:0f:c1:3b:2b:2d:ea:61:7d:d6:11:63:fb
    - checkout
    - run:
        command: sudo apt-get update && sudo apt-get install -y cpanminus make gcc
        name: Install Perl packages
    - run:
        command: cpanm --quiet --notest Dist::Zilla Dist::Zilla::App::Command::cover
          App::cpm Devel::Cover::Report::Codecov https://cpan.metacpan.org/authors/id/S/SR/SRI/Mojolicious-7.29.tar.gz
          https://cpan.metacpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-7.30.tar.gz
        name: Install dzil
    - run:
        command: |
          source /etc/profile.d/perl5.sh
          cpm install -w 2 --mirror=http://cpan.cpantesters.org/ -g $(dzil authordeps --missing)
        name: Install dzil author deps
    - run:
        command: |
          source /etc/profile.d/perl5.sh
          cpm install -w 2 --mirror=http://cpan.cpantesters.org/ -g $(dzil listdeps --author --missing)
        name: Install distribution deps
    - run:
        command: |
          source /etc/profile.d/perl5.sh
          dzil smoke --release --author && dzil cover -test && dzil xtest
        name: Run test
    working_directory: /home/git/regentmarkets/perl-Data-Validate-Sanctions
version: 2
workflows:
  build-workflow:
    jobs: &1
    - build:
        context: perl
  daily:
    jobs: *1
    triggers:
    - schedule:
        cron: 2 20 * * *
        filters:
          branches:
            only:
            - master
  version: 2
